### ISSUE TITLE
HOW TO USE IT

### ISSUE THREAD

**Issue by HackerGprat** [brookhong/KeyCastOW#20]
I WANT TO USE THIS KEYCASTOW, IN MY DAILY LIFE TO RECORD MY KEYBOARD , 
BUT I DON'T KNOW HOW TO USE YOUR CODE.. TO RUN, 
CAN YOU HELP ME TO RUN IT, 
IS IT FOR WHICH OS, LINUX OR WINODWS OR BOTH?

**Comment by liuxilu** [comment]
WHR ARE YOU SO LOUD !
You'd compile yourself or download [here (chocolatey)](https://chocolatey.org/api/v2/package/keycastow/2.0.2.4) and unpack as a zip.

**Comment by Lemmingh** [comment]
You can find answers easily from other issues.
#5
#6
#7
#10
#13
#15
#19

---

> How to use

1. Install [**Visual Studio**](https://www.visualstudio.com/vs/) with the **Desktop development with C++** workload.
2. Open **Visual Studio**, and load `keycastow.vcxproj`.
3. If it asks to retarget project, click **OK**.
4. Set **Solution Configuration** to **Release**.
5. In **Solution Explorer**, right click project `keycastow`, select **Build**.
6. You will find the **executable `keycastow.exe`** in `Release` subfolder, together with all runtime resources.

---

> Winch OS

**Windows** only.

See `README.md`.

This app relies on Win32 APIs.
And "KeyCastOW" is pronounced as "key cast on Windows".

---

BTW, I suggest you try other applications, since it's evident that the author has deserted the project.

* He has not responded to anything for years.
* He said many antivirus systems hate KeyCastOW.
* KeyCastOW works terribly on HiDPI displays.

**Comment by HackerGprat** [comment]
> WHR ARE YOU SO LOUD !
> You'd compile yourself or download [here (chocolatey)](https://chocolatey.org/api/v2/package/keycastow/2.0.2.4) and unpack as a zip.

I apologize .. BUT I LIKES CAPES LOCK. IT LOOKS SO GOOD, .. 
thank you for reply.. my next step is to find out .. how to use nupkg extension. .lol..

**Comment by HackerGprat** [comment]
> You can find answers easily from other issues.
> #5
> #6
> #7
> #10
> #13
> #15
> #19
> 
> > How to use
> 
> 1. Install [**Visual Studio**](https://www.visualstudio.com/vs/) with the **Desktop development with C++** workload.
> 2. Open **Visual Studio**, and load `keycastow.vcxproj`.
> 3. If it asks to retarget project, click **OK**.
> 4. Set **Solution Configuration** to **Release**.
> 5. In **Solution Explorer**, right click project `keycastow`, select **Build**.
> 6. You will find the **executable `keycastow.exe`** in `Release` subfolder, together with all runtime resources.
> 
> > Winch OS
> 
> **Windows** only.
> 
> See `README.md`.
> 
> This app relies on Win32 APIs.
> And "KeyCastOW" is pronounced as "key cast on Windows".
> 
> BTW, I suggest you try other applications, since it's evident that the author has deserted the project.
> 
> * He has not responded to anything for years.
> * He said many antivirus systems hate KeyCastOW.
> * KeyCastOW works terribly on HiDPI displays.



> You can find answers easily from other issues.
> #5
> #6
> #7
> #10
> #13
> #15
> #19
> 
> > How to use
> 
> 1. Install [**Visual Studio**](https://www.visualstudio.com/vs/) with the **Desktop development with C++** workload.
> 2. Open **Visual Studio**, and load `keycastow.vcxproj`.
> 3. If it asks to retarget project, click **OK**.
> 4. Set **Solution Configuration** to **Release**.
> 5. In **Solution Explorer**, right click project `keycastow`, select **Build**.
> 6. You will find the **executable `keycastow.exe`** in `Release` subfolder, together with all runtime resources.
> 
> > Winch OS
> 
> **Windows** only.
> 
> See `README.md`.
> 
> This app relies on Win32 APIs.
> And "KeyCastOW" is pronounced as "key cast on Windows".
> 
> BTW, I suggest you try other applications, since it's evident that the author has deserted the project.
> 
> * He has not responded to anything for years.
> * He said many antivirus systems hate KeyCastOW.
> * KeyCastOW works terribly on HiDPI displays.

Owesome. dude.. you guys just clear my all doubts ... with solutions. +1 respect to @Lemmingh  and +1 to @liuxilu
